<?php

use Illuminate\Database\Seeder;

class EscolaridadeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('escolaridades')->insert([
            [
               'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'CRECHE 3',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2016-04-01',
                'FX_ETARIA_FIM' => '2017-03-31',
                'QTD_VAGAS' => '20',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'CRECHE 3',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2016-04-01',
                'FX_ETARIA_FIM' => '2017-03-31',
                'QTD_VAGAS' => '20',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'CRECHE 3',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2016-04-01',
                'FX_ETARIA_FIM' => '2017-03-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE I',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2015-04-01',
                'FX_ETARIA_FIM' => '2016-03-31',
                'QTD_VAGAS' => '15',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE I',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2015-04-01',
                'FX_ETARIA_FIM' => '2016-03-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE I',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2015-04-01',
                'FX_ETARIA_FIM' => '2016-03-31',
                'QTD_VAGAS' => '15',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE II',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2014-04-01',
                'FX_ETARIA_FIM' => '2015-03-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE II',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2014-04-01',
                'FX_ETARIA_FIM' => '2015-03-31',
                'QTD_VAGAS' => '5',
            ],
            [
                'ESCOLARIDADE' => 'EDUCAÇÃO INFANTIL',
                'ANO' => 'PRE II',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2014-04-01',
                'FX_ETARIA_FIM' => '2015-03-31',
                'QTD_VAGAS' => '15',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '1º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2013-01-01',
                'FX_ETARIA_FIM' => '2014-03-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '1º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2013-01-01',
                'FX_ETARIA_FIM' => '2014-03-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '1º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2013-01-01',
                'FX_ETARIA_FIM' => '2014-03-31',
                'QTD_VAGAS' => '75',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '2º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2012-01-01',
                'FX_ETARIA_FIM' => '2013-12-31',
                'QTD_VAGAS' => '4',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '2º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2012-01-01',
                'FX_ETARIA_FIM' => '2013-12-31',
                'QTD_VAGAS' => '5',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '2º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2012-01-01',
                'FX_ETARIA_FIM' => '2013-12-31',
                'QTD_VAGAS' => '50',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '3º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2011-01-01',
                'FX_ETARIA_FIM' => '2012-12-31',
                'QTD_VAGAS' => '5',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '3º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2011-01-01',
                'FX_ETARIA_FIM' => '2012-12-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '3º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2011-01-01',
                'FX_ETARIA_FIM' => '2012-12-31',
                'QTD_VAGAS' => '30',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '4º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2010-01-01',
                'FX_ETARIA_FIM' => '2011-12-31',
                'QTD_VAGAS' => '0',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '4º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2010-01-01',
                'FX_ETARIA_FIM' => '2011-12-31',
                'QTD_VAGAS' => '0',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '4º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2010-01-01',
                'FX_ETARIA_FIM' => '2011-12-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '5º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2009-01-01',
                'FX_ETARIA_FIM' => '2010-12-31',
                'QTD_VAGAS' => '10',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '5º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2009-01-01',
                'FX_ETARIA_FIM' => '2010-12-31',
                'QTD_VAGAS' => '5',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL I',
                'ANO' => '5º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2009-01-01',
                'FX_ETARIA_FIM' => '2010-12-31',
                'QTD_VAGAS' => '30',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '6º ANO',
                'TURNO' => 'COMPLEMENTAR (INTEGRAL)',
                'FX_ETARIA_INI' => '2008-01-01',
                'FX_ETARIA_FIM' => '2009-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '6º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2008-01-01',
                'FX_ETARIA_FIM' => '2009-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '6º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2008-01-01',
                'FX_ETARIA_FIM' => '2009-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '7º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2007-01-01',
                'FX_ETARIA_FIM' => '2008-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '7º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2007-01-01',
                'FX_ETARIA_FIM' => '2008-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '8º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2006-01-01',
                'FX_ETARIA_FIM' => '2007-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '8º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2006-01-01',
                'FX_ETARIA_FIM' => '2007-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '9º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2005-01-01',
                'FX_ETARIA_FIM' => '2006-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO FUNDAMENTAL II',
                'ANO' => '9º ANO',
                'TURNO' => 'TARDE',
                'FX_ETARIA_INI' => '2005-01-01',
                'FX_ETARIA_FIM' => '2006-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO MÉDIO',
                'ANO' => '1º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2004-01-01',
                'FX_ETARIA_FIM' => '2005-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO MÉDIO',
                'ANO' => '2º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2003-01-01',
                'FX_ETARIA_FIM' => '2004-12-31',
                'QTD_VAGAS' => '40',
            ],
            [
                'ESCOLARIDADE' => 'ENSINO MÉDIO',
                'ANO' => '3º ANO',
                'TURNO' => 'MANHÃ',
                'FX_ETARIA_INI' => '2002-01-01',
                'FX_ETARIA_FIM' => '2003-12-31',
                'QTD_VAGAS' => '40',
            ]
        ]);
    }
}
